"""
Build DPO preference pairs for split-generator fine-tuning.

Goal: teach a model to generate CIDI-quality (epistemically necessary) splits
from a problem text, contrasting them against naive baseline splits.

Strategy
--------
  chosen : CIDI-validated split from Phase 2 results (CDI >= MIN_CDI in C7)
  rejected: naive split generated by gpt-4o-mini with a simple "divide it"
            prompt — produces redundant or asymmetric splits without epistemic design

The training signal: the model should learn to output splits that satisfy
Szewkis positive interdependence (neither agent can solve alone) rather than
arbitrary information divisions.

Output (TRL DPO format)
-----------------------
  outputs/training/split_dpo_train.jsonl
  outputs/training/split_dpo_test.jsonl
  outputs/training/split_dpo_stats.json
  outputs/training/split_dpo_pairs_full.jsonl  (with metadata for analysis)

Usage
-----
  python -m research.training.prepare_split_dpo_data
  python -m research.training.prepare_split_dpo_data --min-cdi 0.5 --seed 42
"""
from __future__ import annotations
import argparse, json, random, textwrap
from pathlib import Path

from research.config import CFG
from research.openai_utils import chat

PILOT_DIR   = Path("outputs/pilot")
TRAIN_DIR   = Path("outputs/training")
OUT_TRAIN   = TRAIN_DIR / "split_dpo_train.jsonl"
OUT_TEST    = TRAIN_DIR / "split_dpo_test.jsonl"
OUT_STATS   = TRAIN_DIR / "split_dpo_stats.json"
OUT_FULL    = TRAIN_DIR / "split_dpo_pairs_full.jsonl"

NAIVE_MODEL = "gpt-4o-mini"
MIN_CDI     = 0.5
TRAIN_FRAC  = 0.8


# ── system prompt for DPO training ────────────────────────────────────────────
# Compact version of the M4 system prompt — sufficient to frame the task
# without the full few-shot examples (those inflate token count in DPO pairs)

_SPLIT_SYSTEM = textwrap.dedent("""\
You are an expert collaborative learning designer for mathematics education.

Given a math problem, create a 2-agent jigsaw split that satisfies these conditions:
1. COMMON GOAL — both agents share an explicit objective (shared_context).
2. POSITIVE INTERDEPENDENCE — neither agent can solve the problem alone with only
   their packet; together they can.
3. INFORMATION PURITY — packets contain only raw mathematical data/conditions,
   never task instructions, never "you need your partner for X".
4. BALANCE — packets have roughly equal informational weight.

Choose the split PATTERN that creates the strongest interdependence:
  SPLIT-C: Complementary conditions (equations/constraints split across agents)
  SPLIT-D: Multi-step chain (agent A computes intermediate; agent B needs it)
  SPLIT-B: Dual representation (same object, different representations)
  SPLIT-A: Composite figure (geometry: each agent sees one component)
  SPLIT-F: Sample space × counting principle (probability/combinatorics)
  SPLIT-G: Hypothesis × key lemma (proofs/number theory)
  SPLIT-E: Objective × constraints (optimization)

Return ONLY valid JSON:
{
  "pattern": "<SPLIT-A|B|C|D|E|F|G>",
  "shared_context": "<goal statement — NO mathematical data>",
  "packets": [
    {"agent_id": 1, "information": "<raw data/condition for agent 1>"},
    {"agent_id": 2, "information": "<raw data/condition for agent 2>"}
  ],
  "interdependence_check": {
    "agent1_can_answer_alone": false,
    "agent2_can_answer_alone": false,
    "combined_can_answer": true
  }
}
""").strip()


# ── naive split prompt ────────────────────────────────────────────────────────
# Deliberately simple — no Szewkis conditions, no interdependence requirement.
# This produces the "rejected" splits: arbitrary/redundant divisions.

_NAIVE_SYSTEM = textwrap.dedent("""\
Divide the following math problem into two parts for two students.
Simply split the mathematical information in half — give student A some data
and student B the rest. No need to ensure they need each other.

Return ONLY valid JSON:
{
  "pattern": "SPLIT-D",
  "shared_context": "<the question or goal>",
  "packets": [
    {"agent_id": 1, "information": "<some of the problem information>"},
    {"agent_id": 2, "information": "<the remaining problem information>"}
  ],
  "interdependence_check": {
    "agent1_can_answer_alone": null,
    "agent2_can_answer_alone": null,
    "combined_can_answer": true
  }
}
""").strip()


# ── data loading ──────────────────────────────────────────────────────────────

def _load_best_c7(min_cdi: float) -> dict[str, dict]:
    """
    For each problem, keep the C7 result with the highest CDI >= min_cdi.
    Must have: valid N=2 split with raw_split dict.
    Uses ALL problems (not restricted to phase1 filtered set) to maximize training data.
    """
    best: dict[str, tuple[float, dict]] = {}
    for f in sorted(PILOT_DIR.glob("math_*_C7_*.json")):
        parts = f.stem.split("_")
        if len(parts) < 5:
            continue
        pid = f"{parts[0]}_{parts[1]}"
        try:
            d = json.loads(f.read_text())
        except Exception:
            continue
        if "error" in d:
            continue
        split = d.get("split", {})
        if not isinstance(split, dict) or not split.get("valid"):
            continue
        if not isinstance(split.get("raw_split"), dict):
            continue
        if len(split.get("packets", [])) != 2:
            continue
        cdi = d.get("cdi", 0.0) or 0.0
        if cdi < min_cdi:
            continue
        prev_cdi, _ = best.get(pid, (-1.0, {}))
        if cdi > prev_cdi:
            best[pid] = (cdi, d)
    return {pid: d for pid, (_, d) in best.items()}


# ── naive split generation ────────────────────────────────────────────────────

def _generate_naive_split(problem: str) -> dict | None:
    """Ask gpt-4o-mini to produce a naive (non-epistemic) split."""
    try:
        raw = chat(
            messages=[
                {"role": "system", "content": _NAIVE_SYSTEM},
                {"role": "user",   "content": f"PROBLEM:\n{problem}"},
            ],
            model=NAIVE_MODEL,
            temperature=0.7,   # some variation to ensure it's not identical to CIDI split
            json_mode=True,
            max_tokens=600,
        )
        return json.loads(raw)
    except Exception as e:
        print(f"  [WARN] naive split failed: {e}")
        return None


# ── pair building ─────────────────────────────────────────────────────────────

def _build_messages(problem: str, split_json: dict) -> list[dict]:
    """Format as a 3-turn conversation for TRL DPO."""
    return [
        {"role": "system",    "content": _SPLIT_SYSTEM},
        {"role": "user",      "content": f"PROBLEM:\n{problem}"},
        {"role": "assistant", "content": json.dumps(split_json, ensure_ascii=False)},
    ]


def _is_naive_inferior(chosen_raw: dict, naive_raw: dict) -> bool:
    """
    Heuristic check: naive split is inferior if its interdependence_check
    is null/missing or if its packets look identical to the chosen ones.
    Returns True if the pair is usable (they differ meaningfully).
    """
    if naive_raw is None:
        return False
    # Reject if packets are identical or nearly identical
    c_pkts = [str(p.get("information", "")) for p in chosen_raw.get("packets", [])]
    n_pkts = [str(p.get("information", "")) for p in naive_raw.get("packets", [])]
    if c_pkts == n_pkts:
        return False
    # Reject if naive interdependence_check claims both can answer alone
    naive_ic = naive_raw.get("interdependence_check", {}) or {}
    if naive_ic.get("agent1_can_answer_alone") and naive_ic.get("agent2_can_answer_alone"):
        return False  # both redundant — not useful as a rejected example
    return True


def build_pairs(best_c7: dict[str, dict]) -> list[dict]:
    pairs = []
    pids = sorted(best_c7.keys())
    print(f"[INFO] Generating naive splits for {len(pids)} problems...")
    for i, pid in enumerate(pids):
        d        = best_c7[pid]
        split    = d["split"]
        problem  = split.get("problem", "")
        chosen_r = split["raw_split"]

        naive_r = _generate_naive_split(problem)
        if not _is_naive_inferior(chosen_r, naive_r):
            print(f"  [{i+1:>3}] {pid}  SKIP (naive indistinguishable or None)")
            continue

        # Strip M4-specific metadata fields not needed for training
        chosen_clean = {k: chosen_r[k] for k in
                        ["pattern", "shared_context", "packets", "interdependence_check"]
                        if k in chosen_r}
        naive_clean  = {k: naive_r[k]  for k in
                        ["pattern", "shared_context", "packets", "interdependence_check"]
                        if k in naive_r}

        pairs.append({
            "problem_id":   pid,
            "cdi_chosen":   d.get("cdi", 0.0),
            "problem":      problem,
            "chosen_raw":   chosen_clean,
            "rejected_raw": naive_clean,
            "chosen":       _build_messages(problem, chosen_clean),
            "rejected":     _build_messages(problem, naive_clean),
        })
        print(f"  [{i+1:>3}] {pid}  CDI={d.get('cdi',0):.3f}  OK")

    return pairs


# ── train / test split ────────────────────────────────────────────────────────

def _split_by_problem(pairs: list[dict],
                      train_frac: float,
                      seed: int) -> tuple[list[dict], list[dict]]:
    pids = sorted({p["problem_id"] for p in pairs})
    rng  = random.Random(seed)
    rng.shuffle(pids)
    cut  = int(len(pids) * train_frac)
    train_pids = set(pids[:cut])
    return (
        [p for p in pairs if p["problem_id"] in  train_pids],
        [p for p in pairs if p["problem_id"] not in train_pids],
    )


# ── main ──────────────────────────────────────────────────────────────────────

def prepare(min_cdi: float = MIN_CDI,
            train_frac: float = TRAIN_FRAC,
            seed: int = 42) -> tuple[list[dict], list[dict]]:
    TRAIN_DIR.mkdir(parents=True, exist_ok=True)

    print(f"[INFO] Loading best C7 splits (CDI >= {min_cdi})...")
    best_c7 = _load_best_c7(min_cdi)
    print(f"       {len(best_c7)} problems")

    pairs = build_pairs(best_c7)
    print(f"\n[INFO] Usable pairs: {len(pairs)} / {len(best_c7)}")

    train_pairs, test_pairs = _split_by_problem(pairs, train_frac, seed)

    def _write_jsonl(records: list[dict], path: Path) -> None:
        with open(path, "w", encoding="utf-8") as f:
            for r in records:
                out = {"chosen": r["chosen"], "rejected": r["rejected"]}
                f.write(json.dumps(out, ensure_ascii=False) + "\n")

    _write_jsonl(train_pairs, OUT_TRAIN)
    _write_jsonl(test_pairs,  OUT_TEST)

    # Full records with metadata for analysis
    with open(OUT_FULL, "w", encoding="utf-8") as f:
        for r in pairs:
            f.write(json.dumps(r, ensure_ascii=False) + "\n")

    stats = {
        "total_pairs":    len(pairs),
        "skipped":        len(best_c7) - len(pairs),
        "train_pairs":    len(train_pairs),
        "test_pairs":     len(test_pairs),
        "train_problems": len({p["problem_id"] for p in train_pairs}),
        "test_problems":  len({p["problem_id"] for p in test_pairs}),
        "cdi_chosen_mean": round(sum(p["cdi_chosen"] for p in pairs) / len(pairs), 3) if pairs else 0,
        "min_cdi_filter": min_cdi,
        "seed": seed,
    }
    OUT_STATS.write_text(json.dumps(stats, indent=2))

    print(f"\n[OK] {OUT_TRAIN}  ({len(train_pairs)} pairs)")
    print(f"[OK] {OUT_TEST}   ({len(test_pairs)} pairs)")
    print(f"[OK] {OUT_STATS}")
    print(f"     chosen CDI mean: {stats['cdi_chosen_mean']}")
    return train_pairs, test_pairs


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--min-cdi",    type=float, default=MIN_CDI)
    parser.add_argument("--train-frac", type=float, default=TRAIN_FRAC)
    parser.add_argument("--seed",       type=int,   default=42)
    args = parser.parse_args()
    prepare(min_cdi=args.min_cdi, train_frac=args.train_frac, seed=args.seed)


if __name__ == "__main__":
    main()
